mlspec_base_type:
  # Base schema type that this extends
  meta: base

mlspec_schema_version:
  # Identifies the version of this schema
  meta: 500.0.1

mlspec_schema_type:
  # Identifies the type of this schema
  meta: training_run

schema_version:
  # Identifies version of MLSpec to use to instantiate
  type: semver
  required: True

schema_type:
  type: string
  required: True

nodes:
  type: int
  required: True

cpu_per_node:
  type: int
  required: True

ram_per_node:
  type: string
  required: True

gpu_required:
  type: boolean
  required: True

output_path:
  type: path
  required: True

training_params:
  # training_params: (Optional) list of hyperparameters for the training model
  type: nested
  schema:
    learning_rate:
      type: float
      required: True
    loss:
      type: float
      required: True
    batch_size:
      type: float
      required: True
    epoch:
      type: float
      required: True
    optimizer:
      # Momentum
      type: list_strings
      required: True
    train_op:
      type: string
      required: True
    other_tags:
      #variable_update=replicated
      #gradient_repacking=8
      #num_gpus=2
      #num_batches=10000
      # weight_decay=1e-4
      type: dict
      required: True
base_image:
  type: string
  required: True

machine_type:
  type: string
  required: True

